return {

	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	opts = {
		ensure_installed = {
			"arduino",
			"asm",
			"bash",
			"c",
			"c_sharp",
			"cmake",
			"comment",
			"commonlisp",
			"cpp",
			"css",
			"csv",
			"d",
			"dart",
			"diff",
			"disassembly",
			"gitattributes",
			"gitcommit",
			"gitignore",
			"go",
			"gomod",
			"gosum",
			"html",
			"http",
			"hyprlang",
			"ini",
			"java",
			"javascript",
			"jq",
			"jsdoc",
			"json",
			"json5",
			"jsonnet",
			"julia",
			"kotlin",
			"latex",
			"llvm",
			"lua",
			"luadoc",
			"make",
			"markdown_inline",
			"matlab",
			"meson",
			"nasm",
			"objdump",
			"ocaml",
			"ocamllex",
			"odin",
			"pascal",
			"perl",
			"php",
			"python",
			"r",
			"regex",
			"ruby",
			"rust",
			"scss",
			"sql",
			"typescript",
			"typespec",
			"udev",
			"v",
			"vim",
			"vimdoc",
			"vue",
			"xml",
			"yaml",
			"yuck",
			"zig",
			"ziggy",
		},
		auto_install = false,
		highlight = {
			enable = true,
			-- Some languages depend on vim's regex highlighting system (such as Ruby) for indent rules.
			--  If you are experiencing weird indenting issues, add the language to
			--  the list of additional_vim_regex_highlighting and disabled languages for indent.
			additional_vim_regex_highlighting = { "ruby" },
		},
		indent = { enable = true, disable = { "ruby" } },
		matchup = {
			enable = true,
		},
	},
	config = function(_, opts)
		---@diagnostic disable-next-line: missing-fields
		require("nvim-treesitter.configs").setup(opts)
		vim.api.nvim_set_hl(0, "@variable", { fg = "#00ffa5" })
		vim.api.nvim_set_hl(0, "LspInlayHint", { bg = "#1a1b26" })
	end,
}
